services:
  weather:
    container_name: weather
    build:
      context: .
      # target: dev
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: always
    develop:
      watch:
        - action: sync
          path: ./
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:  # Añade esta sección